version: "3"
services:
  app:
    container_name: app
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "3000:3000"
      - "80:3000"
    links:
      - mongo
    environment:
      DB_HOST: mongodb://mongo:27017
    command: /bin/bash -c "node seeds/seed.js && npm run start"
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
